version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
      - "9999"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.9.20.150
      #KAFKA_ADVERTISED_HOST_NAME: 10.131.126.233
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.212
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock